#!/bin/sh

ACTION="imi_electron_init_script_${1}"

# mount point path
MP=$(get custom_partition.mountpoint)
# custom partition path
CP="${MP}/imi_electron"
# output to systemlog with ID amd tag
LOGGER="logger -it ${ACTION}"

echo "Starting" | $LOGGER

case "$1" in
init)
 	chown -R user:users ${CP}/userhome /userhome/.config/IMI_Config_Changer.json

	# Initial permissions
	chown -R 0:0 "${CP}" | $LOGGER
	chmod 755 "${MP}" | $LOGGER
	# Linking files and folders on proper path
	find "${CP}" | while read LINE
	do
		DEST=$(echo -n "${LINE}" | sed -e "s|${CP}||g")
		if [ ! -z "${DEST}" -a ! -e "${DEST}" ]; then
			# Remove the last slash, if it is a dir
			[ -d $LINE ] && DEST=$(echo "${DEST}" | sed -e "s/\/$//g") | $LOGGER
			if [ ! -z "${DEST}" ]; then
				ln -sv "${LINE}" "${DEST}" | $LOGGER
			fi
		fi
	done
;;
stop)
	#killall MYAPPNAME
	#sleep 3
;;
esac

echo "Finished" | $LOGGER

exit 0
